import { DISCHARGEFIELDMASTER_MODEL } from "./discharge_field_master.model.js";

class Discharge_field_masterService {
  async getAll() {
  const count = await DISCHARGEFIELDMASTER_MODEL.countDocuments();
  if (count === 0) {
  const defaultFields = [
  { name: "causeOfDeath", label: "CAUSE OF DEATH", type: "richtext", summarySection: "", status: false },
  { name: "ifDeathThenCauseOfDeath", label: "If Death then cause of death", type: "text", summarySection: "", status: false },
  { name: "crossConsultation", label: "Cross Consultation", type: "richtext", summarySection: "", status: false },
  { name: "diagnosis", label: "Diagnosis", type: "richtext", summarySection: "", status: false },
  { name: "chiefComplaints", label: "Chief Complaints", type: "richtext", summarySection: "", status: false },
  { name: "pastHistory", label: "PAST HISTORY", type: "richtext", summarySection: "", status: false },
  { name: "courseInHospital", label: "Course In Hospital", type: "richtext", summarySection: "", status: false },
  { name: "investigation", label: "Investigation", type: "richtext", summarySection: "", status: false },
  { name: "treatmentGivenOperativeNotesCourse", label: "Treatment Given / Operative Notes / Course in the Hospital", type: "richtext", summarySection: "", status: false },
  { name: "treatmentGiven", label: "Treatment Given", type: "text", summarySection: "", status: false },
  { name: "treatmentAdvised", label: "Treatment Advised", type: "richtext", summarySection: "", status: false },
  { name: "conditionAtTheTimeOfDischarge", label: "Condition at the time of Discharge", type: "text", summarySection: "", status: false },
  { name: "adviceAtDischarge", label: "Advice at Discharge", type: "richtext", summarySection: "", status: false },
  { name: "mlcNo", label: "MLC No.", type: "text", summarySection: "", status: false },
  { name: "followUpDate", label: "Follow Up Date", type: "text", summarySection: "", status: false },
  { name: "adviceOnFollowUp", label: "Advice On Follow Up", type: "richtext", summarySection: "", status: false },
  { name: "personalHistory", label: "Personal History", type: "text", summarySection: "", status: false },
  { name: "marriedSince", label: "Married Since", type: "text", summarySection: "", status: false },
  { name: "doctorRegNo", label: "Doctor Reg. No.", type: "text", summarySection: "", status: false },
  { name: "procedureDone", label: "Procedure Done", type: "text", summarySection: "", status: false },
  { name: "ecg", label: "ECG", type: "text", summarySection: "", status: false },
  { name: "onExamination", label: "On Examination", type: "text", summarySection: "", status: false },
  { name: "xrayChest", label: "X-Ray Chest", type: "text", summarySection: "", status: false },
  { name: "otherXray", label: "Other X-Ray", type: "text", summarySection: "", status: false },
  { name: "twoDEcho", label: "2D ECHO", type: "text", summarySection: "", status: false },
  { name: "usg", label: "USG", type: "text", summarySection: "", status: false },
  { name: "ctScan", label: "CT SCAN", type: "text", summarySection: "", status: false },
  { name: "placenta", label: "Placenta", type: "text", summarySection: "", status: false },
  { name: "treatmentCarePlan", label: "Treatment Care Plan", type: "text", summarySection: "", status: false },
  { name: "mriScan", label: "MRI SCAN", type: "text", summarySection: "", status: false },
  { name: "deliveryNotes", label: "Delivery Notes", type: "text", summarySection: "", status: false },
  { name: "infant", label: "Infant", type: "text", summarySection: "", status: false },
  { name: "lscs", label: "LSCS", type: "text", summarySection: "", status: false },
  { name: "status", label: "Status", type: "text", summarySection: "", status: false },
  { name: "municipalBirthRegNo", label: "Municipal Birth reg No", type: "text", summarySection: "", status: false },
  { name: "regDate", label: "Reg Date", type: "text", summarySection: "", status: false },
  { name: "vaccination", label: "Vaccination", type: "text", summarySection: "", status: false },
  { name: "treatmentAdvisedForBaby", label: "Treatment Advised For Baby", type: "text", summarySection: "", status: false },
  { name: "deathSummary", label: "Death Summary", type: "text", summarySection: "", status: false },
  { name: "referencesTaken", label: "References Taken", type: "text", summarySection: "", status: false },
  { name: "howAndWhenToObtainEmergencyCare", label: "How and When to Obtain Emergency Care", type: "text", summarySection: "", status: false },
  { name: "familyHistory", label: "Family H/O", type: "text", summarySection: "", status: false },
  { name: "toAttendOpdOnDate", label: "To Attend O.P.D. On Date", type: "text", summarySection: "", status: false },
  { name: "withDr", label: "With Dr.", type: "text", summarySection: "", status: false },
  { name: "testRequested", label: "Test Requested", type: "text", summarySection: "", status: false },
  { name: "investigationAdvisedOnFu", label: "Investigation Advised On F/U", type: "text", summarySection: "", status: false },
  { name: "consentForDischargeSummary", label: "Consent for Discharge Summery", type: "text", summarySection: "", status: false },
  { name: "preOperativeCourse", label: "Pre Operative Course", type: "text", summarySection: "", status: false },
  { name: "postOperativeCourse", label: "Post Operative Course", type: "text", summarySection: "", status: false },
  { name: "specialHomeCareAdvice", label: "Special Home Care Advice", type: "text", summarySection: "", status: false },
  { name: "drugAllergy", label: "Drug Allergy", type: "text", summarySection: "", status: false },
  { name: "fundus", label: "Fundus", type: "text", summarySection: "", status: false },
  { name: "onRxMonthYear", label: "On Rx Month/Year", type: "text", summarySection: "", status: false },
  { name: "surgicalNotes", label: "Surgical Notes", type: "text", summarySection: "", status: false },
  { name: "maternalHistory", label: "Maternal History", type: "text", summarySection: "", status: false },
  { name: "abg", label: "ABG", type: "text", summarySection: "", status: false },
  { name: "bslChart", label: "BSL Chart", type: "text", summarySection: "", status: false },
  { name: "closure", label: "Closure", type: "text", summarySection: "", status: false },
  { name: "vision", label: "Vision", type: "text", summarySection: "", status: false },
  { name: "cultureReport", label: "Culture Report", type: "text", summarySection: "", status: false },
  { name: "antSeg", label: "Ant. Seg.", type: "text", summarySection: "", status: false },
  { name: "iop", label: "IOP", type: "text", summarySection: "", status: false },
  { name: "sac", label: "SAC", type: "text", summarySection: "", status: false },
  { name: "firNo", label: "FIR No.", type: "text", summarySection: "", status: false },
  { name: "biopsy", label: "Biopsy", type: "text", summarySection: "", status: false },
  { name: "generalPhysicalExamination", label: "General Physical Examination", type: "text", summarySection: "", status: false },
  { name: "ascan", label: "Ascan", type: "text", summarySection: "", status: false },
  { name: "foodDrugInteraction", label: "Food-drug Interaction", type: "text", summarySection: "", status: false },
  { name: "adviceByConsultant", label: "Advice By Consultant", type: "text", summarySection: "", status: false },
  { name: "painManagementTechniques", label: "Pain Management Techniques", type: "text", summarySection: "", status: false },
  { name: "developmentalHistory", label: "DEVELOPMENTAL HISTORY", type: "text", summarySection: "", status: false },
  { name: "immunizationHistory", label: "IMMUNIZATION HISTORY", type: "text", summarySection: "", status: false },
  { name: "significantMedication", label: "SIGNIFICANT MEDICATION", type: "text", summarySection: "", status: false },
  { name: "anthropometry", label: "ANTHROPOMETRY", type: "text", summarySection: "", status: false },
  { name: "signsOfDeath", label: "SIGNS OF DEATH", type: "text", summarySection: "", status: false },
  { name: "relevantFamilyHistory", label: "Relevant Family History", type: "text", summarySection: "", status: false },
  { name: "occupationalTherapy", label: "Occupational Therapy", type: "text", summarySection: "", status: false },
  { name: "mseAtAdmission", label: "MSE at Admission", type: "text", summarySection: "", status: false },
  { name: "mseAtDischarge", label: "MSE at Discharge", type: "text", summarySection: "", status: false },
  { name: "psychotherapySessions", label: "Psychotherapy Sessions", type: "text", summarySection: "", status: false },
  { name: "modeOfInjury", label: "Mode of Injury", type: "text", summarySection: "", status: false },
  { name: "dressing", label: "Dressing", type: "text", summarySection: "", status: false },
  { name: "significantDiagnosticFindings", label: "Significant Diagnostic Findings", type: "text", summarySection: "", status: false },
  { name: "instructionOnDischarged", label: "Instruction on Discharged", type: "text", summarySection: "", status: false },
  { name: "images", label: "Images", type: "text", summarySection: "", status: false },
  { name: "previousTreatment", label: "Previous Treatment", type: "text", summarySection: "", status: false },
  { name: "weight", label: "Weight", type: "text", summarySection: "", status: false },
  { name: "kco", label: "K/C/O", type: "text", summarySection: "", status: false },
  { name: "drugsAdvices", label: "Drugs Advices", type: "text", summarySection: "", status: false },
  { name: "progressiveReport", label: "Progressive Report", type: "text", summarySection: "", status: false },
  { name: "babyDob", label: "Baby D.O.B.", type: "text", summarySection: "", status: false },
  { name: "babyGender", label: "Baby Gender", type: "text", summarySection: "", status: false },
  { name: "psychosocialHistory", label: "Psycocial History", type: "text", summarySection: "", status: false },
  { name: "bloodGroup", label: "Blood Group", type: "text", summarySection: "", status: false },
  { name: "nameOfSurgery", label: "Name of Surgery", type: "text", summarySection: "", status: false },
  { name: "specialExamination", label: "Special Examination", type: "text", summarySection: "", status: false },
  { name: "localExamination", label: "Local Examination", type: "text", summarySection: "", status: false },
  { name: "historyGivenBy", label: "History Given By", type: "text", summarySection: "", status: false },
  { name: "bloodInvestigation", label: "Blood Investigation", type: "text", summarySection: "", status: false },
  { name: "transferDetails", label: "Transfer Details", type: "text", summarySection: "", status: false },
  { name: "precautions", label: "Precautions", type: "text", summarySection: "", status: false },
  { name: "motherDetails", label: "Mother Details", type: "text", summarySection: "", status: false },
  { name: "babyDetails", label: "Baby Details", type: "text", summarySection: "", status: false },
  { name: "emergencyFollowUpAdviceList", label: "Emergency Follow Up Advice List", type: "text", summarySection: "", status: false },
  { name: "conditionAtTheTimeOfAdmission", label: "Condition at the time of Admission", type: "text", summarySection: "", status: false },
  { name: "lmp", label: "LMP", type: "text", summarySection: "", status: false },
  { name: "relevantInvestigation", label: "Relevant Investigation", type: "text", summarySection: "", status: false },
  { name: "catheterInsertedUnderGuidanceOfSonography", label: "Catheter Inserted Under The Guidance Of Sonography", type: "text", summarySection: "", status: false },
  { name: "nonInvasiveProcedure", label: "Non Invasive Procedure", type: "text", summarySection: "", status: false },
  { name: "postOpInvestigations", label: "Post-op Investigations", type: "text", summarySection: "", status: false },
  { name: "department", label: "Department", type: "text", summarySection: "", status: false },
  { name: "firstTrimester", label: "1st Trimester", type: "text", summarySection: "", status: false },
  { name: "secondTrimester", label: "2nd Trimester", type: "text", summarySection: "", status: false },
  { name: "thirdTrimester", label: "3rd Trimester", type: "text", summarySection: "", status: false },
  { name: "investigationAdvice", label: "Investigation Advice", type: "text", summarySection: "", status: false },
  { name: "icpm", label: "ICPM", type: "text", summarySection: "", status: false },
  { name: "anaesthesia", label: "Anaesthesia", type: "text", summarySection: "", status: false },
  { name: "histopathologyReport", label: "Histopathology Report", type: "text", summarySection: "", status: false },
  { name: "radiologicalInvestigation", label: "Radiological Investigation", type: "text", summarySection: "", status: false },
  { name: "pathologicalInvestigation", label: "Pathological Investigation", type: "text", summarySection: "", status: false },
  { name: "referralConsultants", label: "Referral Consultants", type: "text", summarySection: "", status: false },
  { name: "chiefConsultant", label: "Chief Consultant", type: "text", summarySection: "", status: false },
  { name: "management", label: "Management", type: "text", summarySection: "", status: false },
  { name: "gestationAtDelivery", label: "Gestation At Delivery", type: "text", summarySection: "", status: false },
  { name: "package", label: "Package", type: "text", summarySection: "", status: false },
  { name: "indication", label: "Indication", type: "text", summarySection: "", status: false },
  { name: "specimens", label: "Specimens", type: "text", summarySection: "", status: false },
  { name: "hysteroscopicPolypectomy", label: "Hysteroscopic Polypectomy", type: "text", summarySection: "", status: false },
  { name: "dhl", label: "DHL", type: "text", summarySection: "", status: false },
  { name: "totalLaparoscopicHysterectomy", label: "Total Laparoscopic Hysterectomy", type: "text", summarySection: "", status: false },
  { name: "patientAddress", label: "Patient Address", type: "text", summarySection: "", status: false },
  { name: "intraopFindings", label: "Intraop Findings", type: "text", summarySection: "", status: false },
  { name: "companyNameTpa", label: "Comapny Name & TPA", type: "text", summarySection: "", status: false },
  { name: "perAbd", label: "Per Abd (Abdominal/Abdomen)", type: "text", summarySection: "", status: false },
  { name: "pelvicExam", label: "Pelvic Exam", type: "text", summarySection: "", status: false },
  { name: "laparoscopicTubalLigation", label: "Laparoscopic Tubal Ligation", type: "text", summarySection: "", status: false },
  { name: "operationDetails", label: "Operation Details", type: "text", summarySection: "", status: false },
  { name: "delivery", label: "Delivery", type: "text", summarySection: "", status: false },
  { name: "instructions", label: "Instructions", type: "text", summarySection: "", status: false },
  { name: "anyChronicIllness", label: "Any Chronic illness", type: "text", summarySection: "", status: false },
  { name: "pastHistoryWithDuration", label: "Past History (with duration)", type: "text", summarySection: "", status: false },
  { name: "physiotherapy", label: "Physiotherapy", type: "text", summarySection: "", status: false },
  { name: "anySurgery", label: "Any Surgery", type: "text", summarySection: "", status: false },
  { name: "gpe", label: "GPE", type: "text", summarySection: "", status: false },
  { name: "systemExamination", label: "System Examination", type: "text", summarySection: "", status: false },
  { name: "investigationInTabularForm", label: "Investigation in Tabular Form", type: "text", summarySection: "", status: false },
  { name: "events", label: "Events", type: "text", summarySection: "", status: false },
  { name: "followUpWithPriorAppointment", label: "Follow up with Prior appointment", type: "text", summarySection: "", status: false },
  { name: "reportToHospital", label: "Report to Hospital", type: "text", summarySection: "", status: false },
  { name: "diet", label: "Diet", type: "text", summarySection: "", status: false },
  { name: "additionalAdvice", label: "Additional Advice", type: "text", summarySection: "", status: false },
  { name: "others", label: "Others", type: "text", summarySection: "", status: false },
  { name: "uppercaseReport", label: "Uppercase Report", type: "text", summarySection: "", status: false },
  { name: "examination", label: "Examination", type: "text", summarySection: "", status: false },
  { name: "history", label: "History", type: "text", summarySection: "", status: false },
  { name: "operativeNotesTabular", label: "Operative Notes Tabular", type: "text", summarySection: "", status: false },
  { name: "postNatalDischargeNotes", label: "POST NATAL DISCHARGE NOTES", type: "text", summarySection: "", status: false },
  { name: "anthropometry2", label: "ANTHROPOMETRY", type: "text", summarySection: "", status: false },
  { name: "antenatalHistory", label: "ANTENATAL HISTORY", type: "text", summarySection: "", status: false },
  { name: "birthDetails", label: "BIRTH DETAILS", type: "text", summarySection: "", status: false },
  { name: "clinicalExamination", label: "CLINICAL EXAMINATION", type: "text", summarySection: "", status: false },
  { name: "newbornMetabolicScreening", label: "NEWBORN METABOLIC SCREENING", type: "text", summarySection: "", status: false },
  { name: "recommendations", label: "RECOMMENDATIONS", type: "text", summarySection: "", status: false },
  { name: "adviceToMother", label: "ADVICE TO MOTHER", type: "text", summarySection: "", status: false },
  { name: "adviceToBaby", label: "ADVICE TO BABY", type: "text", summarySection: "", status: false },
  { name: "dangerSigns", label: "DANGER SIGNS", type: "text", summarySection: "", status: false },
  { name: "physicalExamination", label: "PHYSICAL EXAMINATION", type: "text", summarySection: "", status: false },
  { name: "admissionCourse", label: "ADMISSION COURSE", type: "text", summarySection: "", status: false },
  { name: "onExaminationAtTimeOfDischarge", label: "On Examination At Time of Discharge", type: "text", summarySection: "", status: false },
  { name: "birthCertificateNo", label: "Birth Certificate No", type: "text", summarySection: "", status: false },
  { name: "typeOfDischarge", label: "Type of Discharge", type: "text", summarySection: "", status: false },
  { name: "menstrualHistory", label: "Menstrual History", type: "text", summarySection: "", status: false },
  { name: "obstetricsHistory", label: "Obstetrics History", type: "text", summarySection: "", status: false },
  { name: "significantFinding", label: "Significant Finding", type: "text", summarySection: "", status: false },
  { name: "clinicalFindingsAndSummary", label: "Clinical Findings And Summary", type: "text", summarySection: "", status: false },
  { name: "dateOfSurgery", label: "Date of Surgery", type: "text", summarySection: "", status: false },
  { name: "medicalHistory", label: "Medical History", type: "text", summarySection: "", status: false },
  { name: "surgicalHistory", label: "Surgical History", type: "text", summarySection: "", status: false },
  { name: "radiologyUltraSonography", label: "Radiology / Ultra Sonography", type: "text", summarySection: "", status: false },
  { name: "gpla", label: "GPLA", type: "text", summarySection: "", status: false },
  { name: "provisionalDiagnosis", label: "Provisional Diagnosis", type: "text", summarySection: "", status: false },
  { name: "reasonForAdmission", label: "Reason For Admission", type: "text", summarySection: "", status: false },
  { name: "vaccinationDetails", label: "Vaccination Details", type: "text", summarySection: "", status: false },
  { name: "emergencyFollowUpAdvice", label: "Emergency Follow Up Advice", type: "text", summarySection: "", status: false },
  { name: "treatmentOnDischarge", label: "Treatment on Discharge", type: "text", summarySection: "", status: false },
  { name: "historyOfPresentIllness", label: "History of Present Illness", type: "text", summarySection: "", status: false },
  { name: "adviceByDietician", label: "Advice By Dietician", type: "text", summarySection: "", status: false },
  { name: "whenAndHowToObtainUrgentCare", label: "When And How To Obtain Urgent Care", type: "text", summarySection: "", status: false },
  { name: "phototherapy", label: "Phototherapy", type: "text", summarySection: "", status: false },
  { name: "documents", label: "Documents", type: "text", summarySection: "", status: false },
  { name: "prognosis", label: "Prognosis", type: "text", summarySection: "", status: false },
  { name: "protocol", label: "Protocol", type: "text", summarySection: "", status: false },
  { name: "cycle", label: "Cycle", type: "text", summarySection: "", status: false },
  { name: "atDischarge", label: "At Discharge", type: "text", summarySection: "", status: false },
  { name: "aiSummary", label: "AI Summary", type: "text", summarySection: "", status: false },
  { name: "pendingReports", label: "Pending Reports", type: "text", summarySection: "", status: false },
  { name: "preventiveCounselling", label: "Preventive Counselling", type: "text", summarySection: "", status: false },
  { name: "whomToContact", label: "Whom to Contact", type: "text", summarySection: "", status: false },
  { name: "whenToContact", label: "When to Contact", type: "text", summarySection: "", status: false },
  { name: "acknowledgement", label: "Acknowledgement", type: "checkbox", summarySection: "", status: false },
  { name: "maternalRiskFactors", label: "Maternal Risk Factors", type: "text", summarySection: "", status: false },
  { name: "lines", label: "Lines", type: "text", summarySection: "", status: false },
  { name: "lengthOfStay", label: "Length of Stay", type: "text", summarySection: "", status: false },
  { name: "genitaliaHernialSites", label: "Genitalia & Hernial Sites", type: "text", summarySection: "", status: false },
  { name: "feeding", label: "Feeding", type: "text", summarySection: "", status: false },
  { name: "cultures", label: "Cultures", type: "text", summarySection: "", status: false },
  { name: "antimicrobials", label: "Antimicrobials", type: "text", summarySection: "", status: false },
  { name: "respSupport", label: "Resp Support", type: "text", summarySection: "", status: false },
  { name: "bloodProducts", label: "Blood Products", type: "text", summarySection: "", status: false },
  { name: "metabolicScreening", label: "Metabolic Screening", type: "text", summarySection: "", status: false },
  { name: "rop", label: "ROP", type: "text", summarySection: "", status: false },
  { name: "eeg", label: "EEG", type: "text", summarySection: "", status: false },
  { name: "cchdScreening", label: "CCHD Screening", type: "text", summarySection: "", status: false },
  { name: "summaryIfChildStayInNursery", label: "Summary If Child Stay in Nursery", type: "text", summarySection: "", status: false },
  { name: "information", label: "Information", type: "text", summarySection: "", status: false },
  { name: "steps", label: "Steps", type: "text", summarySection: "", status: false },
  { name: "lab", label: "Lab", type: "text", summarySection: "", status: false },
  { name: "reference", label: "Reference", type: "text", summarySection: "", status: false },
  { name: "dialysis", label: "Dialysis", type: "text", summarySection: "", status: false },
  { name: "lifeModifications", label: "Life Modifications", type: "text", summarySection: "", status: false },
  { name: "saveAsTemplate", label: "Save As Template", type: "text", otherTitle: "", status: true }
];

    await DISCHARGEFIELDMASTER_MODEL.insertMany(defaultFields);
  }
  return await DISCHARGEFIELDMASTER_MODEL.find();
}

  async update(id, updateData) {
    return await DISCHARGEFIELDMASTER_MODEL.findByIdAndUpdate(id, updateData, { new: true });
  }

  async getById(id) {
    return await DISCHARGEFIELDMASTER_MODEL.findById(id);
  }

  async delete(id) {
    return await DISCHARGEFIELDMASTER_MODEL.findByIdAndDelete(id);
  }
}

export default new Discharge_field_masterService();
